# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-w" do
  name "git-w"
  desc "Git plugin for managing meta-repo workspaces"
  homepage "https://github.com/robertwritescode/git-w"
  version "1.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-w"

  on_macos do
    on_intel do
      url "https://github.com/robertwritescode/git-w/releases/download/v#{version}/git-w_darwin_amd64.tar.gz"
      sha256 "a78997e026bb74ab595ac661ff51df779c268126851fa6a9c5be41cfc70a3046"
    end
    on_arm do
      url "https://github.com/robertwritescode/git-w/releases/download/v#{version}/git-w_darwin_arm64.tar.gz"
      sha256 "f21cbe6ba78a6e092584d879d1593eca2f48af8436b48e8a7bf8b79a0f1233f6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/robertwritescode/git-w/releases/download/v#{version}/git-w_linux_amd64.tar.gz"
      sha256 "f536035dcdb9441a28bdf5af143a7abddbab85bbfd5bbac73265897533157196"
    end
    on_arm do
      url "https://github.com/robertwritescode/git-w/releases/download/v#{version}/git-w_linux_arm64.tar.gz"
      sha256 "363a31ff31f09970f7027e64e4fc67e8548b372b2b1ba252a5b72f17d54832db"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-w"]
    end
  end

  # No zap stanza required
end
