# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-w" do
  version "1.4.0"

  name "git-w"
  desc "Git plugin for managing meta-repo workspaces"
  homepage "https://github.com/robertwritescode/git-w"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-w"

  on_macos do
    on_intel do
      sha256 "236982ca254979eedabaa262d933b2b268980356a22142bc0e48911a4a2ab045"
      url "https://github.com/robertwritescode/git-w/releases/download/v#{version}/git-w_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e51abc875573860140548354674c677e87a51297ca1413d04dfdc9ea82567e66"
      url "https://github.com/robertwritescode/git-w/releases/download/v#{version}/git-w_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "48bd7b5e4096ce5b33b6f0fbafd3cbf0b1b6de85e88c6deb27267fdbebf1f807"
      url "https://github.com/robertwritescode/git-w/releases/download/v#{version}/git-w_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "039ce1d40b485c1e9b765b972eb3c2d3b54f418615a16a8967379c273efd8398"
      url "https://github.com/robertwritescode/git-w/releases/download/v#{version}/git-w_linux_arm64.tar.gz"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-w"] if OS.mac?
  end

  # No zap stanza required
end
