# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-w" do
  version "1.6.0"

  name "git-w"
  desc "Git plugin for managing meta-repo workspaces"
  homepage "https://github.com/robertwritescode/git-w"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-w"

  on_macos do
    on_intel do
      sha256 "ddd5501ceacd0b66bff5e9c06346960d6988730b425ac8896190055aa19cca74"
      url "https://github.com/robertwritescode/git-w/releases/download/v#{version}/git-w_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b024077b7a1b9a23cd0e98cc7b7b931d43ec4328ff3cb0764f76aacb986439c7"
      url "https://github.com/robertwritescode/git-w/releases/download/v#{version}/git-w_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "81057ecd8ec746658b2c29e289098bfda0f60275f4fe804d65571f16a0dcba6a"
      url "https://github.com/robertwritescode/git-w/releases/download/v#{version}/git-w_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "51a21e6f7332b2a44ac6b0b6b5dd084385d7e770494441be2fe75a0a7147976a"
      url "https://github.com/robertwritescode/git-w/releases/download/v#{version}/git-w_linux_arm64.tar.gz"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-w"] if OS.mac?
  end

  # No zap stanza required
end
